kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: pgbouncer
  annotations:
    description: pgbouncer
  labels:
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}    
spec:
  tags:
  - from:
      kind: DockerImage
      name: "{{ .Values.images.pgbouncer.name }}:{{ .Values.images.pgbouncer.tag }}"
    generation: 2
    name: {{ .Values.images.pgbouncer.tag }}
    referencePolicy:
      type: Source
  - from:
      kind: ImageStreamTag
      name: "pgbouncer:{{ .Values.images.pgbouncer.tag }}"
    generation: 2
    name: latest
    referencePolicy:
      type: Source