kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: etl-alpha
  annotations:
    description: BC Parks ETL (Extract, transform, and load) cron job container (Alpha)
  labels:
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}    
spec: {}
