kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: maintenance-main
  annotations:
    description: BC Parks maintenance website
  labels:
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}    
spec: {}
