kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: public-alpha
  annotations:
    description: BC Parks Public (Gatsby) website (Alpha)
  labels:
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}    
spec: {}
