cluster:
  ssoAuthUrl: https://test.loginproxy.gov.bc.ca/auth

images:
  strapi:
    name: image-registry.openshift-image-registry.svc:5000/c1643c-tools/strapi-alpha
    tag: test
  admin:
    name: image-registry.openshift-image-registry.svc:5000/c1643c-tools/admin-alpha
    tag: test
  public:
    name: image-registry.openshift-image-registry.svc:5000/c1643c-tools/public-alpha
    tag: test
  maintenance:
    name: image-registry.openshift-image-registry.svc:5000/c1643c-tools/maintenance-alpha
    tag: test
  etl:
    name: image-registry.openshift-image-registry.svc:5000/c1643c-tools/etl-alpha
    tag: test
  scheduler:
    name: image-registry.openshift-image-registry.svc:5000/c1643c-tools/scheduler-alpha
    tag: test

cms:
  env:
    environment: alpha-test
    externalUrl: https://alpha-test-cms.bcparks.ca

  hpa:
    minReplicas: 1
    maxReplicas: 2

admin:
  env:
    externalUrl: https://alpha-test-staff.bcparks.ca
    publicUrl: https://alpha-test.bcparks.ca

patroni:
  replicas: 1

backup:
  enabled: true

  enironment:
    friendlyName: bcparks.ca CMS Postgres Backup [alpha-test]
    name: c1643c-test

public:
  hpa:
    minReplicas: 1
    maxReplicas: 2

etl:
  enabled: true

scheduler:
  env:
    emailEnabled: true
    emailRecipient: manuji@oxd.com,mike@oxd.com
