cluster:
  domain: apps.gold.devops.gov.bc.ca
  ssoAuthUrl: https://dev.loginproxy.gov.bc.ca/auth
  ssoRealm: bcparks-service-transformation
  ssoClientId: staff-portal

images:
  strapi:
    name: image-registry.openshift-image-registry.svc:5000/c1643c-tools/strapi-main
    tag: latest
  postgres:
    name: image-registry.openshift-image-registry.svc:5000/c1643c-tools/postgresql
    tag: "13"
  pgbouncer:
    name: image-registry.openshift-image-registry.svc:5000/c1643c-tools/pgbouncer
    tag: latest
  admin:
    name: image-registry.openshift-image-registry.svc:5000/c1643c-tools/admin-main
    tag: latest
  public:
    name: image-registry.openshift-image-registry.svc:5000/c1643c-tools/public-main
    tag: latest
  patroni:
    name: image-registry.openshift-image-registry.svc:5000/c1643c-tools/patroni-postgres
    tag: 2.0.1-12.4-latest
  backup:
    name: image-registry.openshift-image-registry.svc:5000/c1643c-tools/backup-container
    tag: postgres-latest
  maintenance:
    name: image-registry.openshift-image-registry.svc:5000/c1643c-tools/maintenance-main
    tag: latest
  redis:
    name: image-registry.openshift-image-registry.svc:5000/c1643c-tools/redis
    tag: 6.2.14-alpine
  etl:
    name: image-registry.openshift-image-registry.svc:5000/c1643c-tools/etl-main
    tag: latest
  scheduler:
    name: image-registry.openshift-image-registry.svc:5000/c1643c-tools/scheduler-main
    tag: latest

cms:
  componentName: cms

  imagePullPolicy: Always

  resources:
    limits:
      cpu: 400m
      memory: 1250Mi
    requests:
      cpu: 75m
      memory: 250Mi

  env:
    nodeEnv: production
    databaseMinConnections: 0
    databaseMaxConnections: 10
    databaseIdleTimeout: 30000
    databaseCreateTimeout: 30000
    databaseAcquireTimeout: 30000
    smtpHost: apps.smtp.gov.bc.ca
    smtpPort: 25
    smtpFrom: noreply@gov.bc.ca
    smtpReplyTo: noreply@gov.bc.ca
    cacheEnabled: true
    cacheType: redis
    cacheTtl: "60000"
    enableGraphQLPlayground: true
    indexName: bcparks-protected-areas    

  service:
    portName: strapi
    port: 1337

  hpa:
    minReplicas: 1
    maxReplicas: 2
    cpuUtilizationThreshold: 125

patroni:
  componentName: patroni

  enabled: true

  replicas: 3

  databaseName: cms

  resources:
    limits:
      cpu: 250m
      memory: 1250Mi
    requests:
      cpu: 100m
      memory: 250Mi

  env:
    maxConnections: 240

  service:
    portName: patroni-leader
    port: 5432

  pvc:
    accessMode: ReadWriteOnce
    storageClassName: netapp-block-standard
    size: 1Gi

pgbouncer:
  enabled: true

  componentName: pgbouncer

  resources:
    limits:
      cpu: 150m
      memory: 150Mi
    requests:
      cpu: 50m
      memory: 50Mi

  env:
    defaultPoolSize: 80
    poolMode: transaction
    maxClientConn: 120

  service:
    portName: pgbouncer
    port: 6432

admin:
  imagePullPolicy: Always

  componentName: admin

  env:
    externalUrl: https://dev-staff.bcparks.ca
    statHolidayApi: https://canada-holidays.ca/api/v1/provinces/BC

  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 50m
      memory: 50Mi

  service:
    portName: admin
    port: 3000

public:
  imagePullPolicy: Always

  componentName: public

  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 50m
      memory: 50Mi

  service:
    portName: public
    port: 3000

  hpa:
    minReplicas: 1
    maxReplicas: 2
    cpuUtilizationThreshold: 125

backup:
  componentName: postgres-backup

  # Disabled by default.  Overriden for TEST and PROD
  enabled: false

  pvc:
    accessMode: ReadWriteOnce
    storageClassName: netapp-file-backup
    size: 1Gi

  schedule: "0 9 * * *"

  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 2
  backoffLimit: 0

  backupStrategy: "rolling"
  backupDir: "/backups/"

  retention:
    numBackups: 5
    dailyBackups: 7
    weeklyBackups: 4
    monthlyBackups: 1

  enironment:
    friendlyName: "bcparks.ca CMS Postgres Backup [dev]"
    name: "c1643c-dev"

  tableSchema: "public"

  resources:
    limits:
      cpu: "1"
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 250Mi

maintenance:
  imagePullPolicy: Always

  componentName: maintenance

  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 20m
      memory: 50Mi

  service:
    portName: maintenance
    port: 3000

redis:
  imagePullPolicy: Always

  componentName: redis

  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 25m
      memory: 64Mi

  service:
    portName: redis
    port: 6379

etl:
  componentName: etl

  # Enabled by default.  Overriden for aplha-dev
  enabled: true
  disableBcwfsCron: true
  disableParkNamesCron: false
  enableBcwfsStandalonePropagation: false

  # Run the cron job every hour at 15 minutes past the hour
  schedule: "15 * * * *"

  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 2
  backoffLimit: 0

  env:
    bcwfsBansApi: https://openmaps.gov.bc.ca/geo/pub/ows?service=WFS&version=2.0.0&request=GetFeature&typeName=WHSE_LAND_AND_NATURAL_RESOURCE.PROT_BANS_AND_PROHIBITIONS_SP&count=50&outputFormat=json
    parkNamesApi: https://test-data.bcparks.ca/api/parks/names?status=established

  resources:
    limits:
      cpu: "1"
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 250Mi

scheduler:
  imagePullPolicy: Always

  componentName: scheduler

  env:
    batchSize: 20
    shapeDataApi: "https://openmaps.gov.bc.ca/geo/pub/ows?service=WFS&version=2.0.0&request=GetFeature&typeName={1}&outputFormat=json&CQL_FILTER=ORCS_PRIMARY%3D%27{0}%27&SrsName=EPSG%3A4326"
    emailEnabled: true
    emailServer: apps.smtp.gov.bc.ca
    emailPort: 25
    emailSender: parksweb@gov.bc.ca
    emailRecipient: parksweb@gov.bc.ca

  resources:
    limits:
      cpu: 100m
      memory: 160Mi
    requests:
      cpu: 10m
      memory: 80Mi
