cluster:
  ssoAuthUrl: https://loginproxy.gov.bc.ca/auth

images:
  strapi:
    tag: prod
  admin:
    tag: prod
  public:
    tag: prod
  maintenance:
    tag: prod
  etl:
    tag: prod
  scheduler:
    tag: prod

cms:
  resources:
    limits:
      cpu: 400m
      memory: 1250Mi
    requests:
      cpu: 175m
      memory: 625Mi

  env:
    environment: prod
    externalUrl: https://cms.bcparks.ca
    cacheTtl: "600000"

  hpa:
    minReplicas: 2
    maxReplicas: 4
    cpuUtilizationThreshold: 65

admin:
  env:
    externalUrl: https://staff.bcparks.ca
    publicUrl: https://bcparks.ca

patroni:
  resources:
    limits:
      cpu: 400m
      memory: 1500Mi
    requests:
      cpu: 200m
      memory: 750Mi
  replicas: 3

  pvc:
    size: 6Gi

backup:
  enabled: true

  pvc:
    size: 6Gi

  enironment:
    friendlyName: bcparks.ca CMS Postgres Backup [prod]
    name: c1643c-prod

public:
  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 100Mi

  hpa:
    minReplicas: 2
    maxReplicas: 8
    cpuUtilizationThreshold: 35

etl:
  env:
    parkNamesApi: https://data.bcparks.ca/api/parks/names?status=established

scheduler:
  env:
    emailEnabled: true
